name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! 🎉
        
        Please search existing issues and discussions before creating a new feature request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have read the project roadmap and documentation
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - Database
        - Authentication
        - Monitoring
        - CI/CD
        - Documentation
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Security improvement
        - Developer experience
        - User experience
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: "Alternative approaches could be..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Important for upcoming work)
        - Medium (Would be nice to have)
        - Low (Not urgent)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], I need [functionality] because [reason]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Paste images or links here...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Please check all that apply
      options:
        - label: This feature requires database changes
        - label: This feature requires API changes
        - label: This feature requires UI changes
        - label: This feature affects security
        - label: This feature affects performance
        - label: This feature requires documentation updates
        - label: This feature requires testing strategy updates

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...