{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "secure-api-system.fullname" . }}-frontend
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.frontend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "secure-api-system.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.frontend.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.frontend.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.backend.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "secure-api-system.fullname" . }}-backend
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "secure-api-system.fullname" . }}-backend
  minReplicas: {{ .Values.backend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backend.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.backend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.backend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.backend.autoscaling.customMetrics }}
    {{- range .Values.backend.autoscaling.customMetrics }}
    - type: {{ .type }}
      {{- if eq .type "Pods" }}
      pods:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        target:
          type: {{ .target.type }}
          {{- if .target.averageValue }}
          averageValue: {{ .target.averageValue }}
          {{- end }}
      {{- else if eq .type "Object" }}
      object:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        describedObject:
          apiVersion: {{ .describedObject.apiVersion }}
          kind: {{ .describedObject.kind }}
          name: {{ .describedObject.name }}
        target:
          type: {{ .target.type }}
          {{- if .target.value }}
          value: {{ .target.value }}
          {{- end }}
      {{- else if eq .type "External" }}
      external:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        target:
          type: {{ .target.type }}
          {{- if .target.value }}
          value: {{ .target.value }}
          {{- end }}
          {{- if .target.averageValue }}
          averageValue: {{ .target.averageValue }}
          {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.backend.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.backend.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}