{{- if .Values.secrets }}
{{- if .Values.secrets.mysql }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-mysql-secret
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  username: {{ .Values.secrets.mysql.username }}
  password: {{ .Values.secrets.mysql.password }}
  {{- if .Values.secrets.mysql.rootPassword }}
  root-password: {{ .Values.secrets.mysql.rootPassword }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.redis }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-redis-secret
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
data:
  password: {{ .Values.secrets.redis.password }}
{{- end }}

{{- if .Values.secrets.app }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-app-secret
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.app.jwtSecret }}
  encryption-key: {{ .Values.secrets.app.encryptionKey }}
{{- end }}

{{- if .Values.secrets.monitoring }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-monitoring-secret
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  {{- if .Values.secrets.monitoring.sentryDsn }}
  sentry-dsn: {{ .Values.secrets.monitoring.sentryDsn }}
  {{- end }}
  {{- if .Values.secrets.monitoring.slackWebhook }}
  slack-webhook: {{ .Values.secrets.monitoring.slackWebhook }}
  {{- end }}
  {{- if .Values.secrets.monitoring.grafanaPassword }}
  grafana-password: {{ .Values.secrets.monitoring.grafanaPassword }}
  {{- end }}
  {{- if .Values.secrets.monitoring.prometheusPassword }}
  prometheus-password: {{ .Values.secrets.monitoring.prometheusPassword }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.backup }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-backup-secret
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
type: Opaque
data:
  {{- if .Values.secrets.backup.s3AccessKey }}
  s3-access-key: {{ .Values.secrets.backup.s3AccessKey }}
  {{- end }}
  {{- if .Values.secrets.backup.s3SecretKey }}
  s3-secret-key: {{ .Values.secrets.backup.s3SecretKey }}
  {{- end }}
  {{- if .Values.secrets.backup.encryptionKey }}
  encryption-key: {{ .Values.secrets.backup.encryptionKey }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.tls.secretName" . }}
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls.cert }}
  tls.key: {{ .Values.secrets.tls.key }}
{{- end }}

{{- if .Values.global.imagePullSecrets }}
{{- range .Values.global.imagePullSecrets }}
{{- if .data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "secure-api-system.namespace" $ }}
  labels:
    {{- include "secure-api-system.labels" $ | nindent 4 }}
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .data }}
{{- end }}
{{- end }}
{{- end }}

{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-prometheus-auth
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  auth: {{ .Values.monitoring.prometheus.auth }}
{{- end }}

{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-api-system.fullname" . }}-grafana-auth
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
type: Opaque
data:
  auth: {{ .Values.monitoring.grafana.auth }}
{{- end }}
{{- end }}