{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-api-system.fullname" . }}-frontend
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "secure-api-system.frontend.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.frontend.service.type "LoadBalancer" }}
  {{- with .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secure-api-system.fullname" . }}-backend
  namespace: {{ include "secure-api-system.namespace" . }}
  labels:
    {{- include "secure-api-system.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
    - port: {{ .Values.backend.actuator.port | default 8081 }}
      targetPort: actuator
      protocol: TCP
      name: actuator
  selector:
    {{- include "secure-api-system.backend.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.backend.service.type "LoadBalancer" }}
  {{- with .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}